### ISSUE TITLE
Data preparation difficulties.

### ISSUE THREAD

**Issue by wanghao2467201558** [slonetime/EBSeg#3]
I noticed that the SAN dataset also references the previous project. To ensure that my reproduction project can proceed smoothly, I hope the author can provide specific details on the data preparation, including the folder structure and the deployment methods for each dataset. Thank you very much.

**Comment by slonetime** [comment]
Sorry for that. Since our dataset preparation process completely follows the instructions of SAN, though SAN references a previous project, we believe if you follow the instructions of them, the prepared datasets will be fine for reproduction. We will consider adding a detailed introduction of the data processing process. However, I have limited time for this lately, and I hope you can understand.

**Comment by wanghao2467201558** [comment]
Fine, thanks for your reply.
